### ISSUE TITLE
Track: Getting Started Plugins

### ISSUE THREAD

**Issue by ashleygmulligan2** [FlatFilers/flatfile-plugins#197]
```[tasklist]
### Tasks
- [ ] https://github.com/FlatFilers/flatfile-plugins/issues/196
- [ ] https://github.com/FlatFilers/flatfile-plugins/issues/194
- [ ] https://github.com/FlatFilers/flatfile-plugins/issues/183
```

**Comment by carlbrugger** [comment]
Tasks completed
